// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file is auto-generated for SF Pro font family.
// Generated at: 2025-11-14T00:00:00Z
// Do not edit this file manually. Any changes will be overwritten on regeneration.
//
// To regenerate, run:
// ```
// flutter pub run build_runner build --delete-conflicting-outputs
// ```

import 'package:flutter/material.dart';
import 'fonts.dart';

/// Generated TextStyle definitions for SF Pro font family
/// Auto-generated typography system with consistent scaling
abstract class SFProTextStyles {
  /// Display Text - Extra Large Heading
  /// Size: 40px, Weight: Bold
  /// Used for: App title, main heading
  static const TextStyle displayBold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.largeDisplay,
    fontWeight: FontWeight.w700,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  /// Display Text - Semi-Bold
  /// Size: 40px, Weight: SemiBold
  static const TextStyle displaySemiBold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.largeDisplay,
    fontWeight: FontWeight.w600,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  /// Display Text - Medium
  /// Size: 40px, Weight: Medium
  static const TextStyle displayMedium = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.largeDisplay,
    fontWeight: FontWeight.w500,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.none,
  );

  /// Display Text - Regular
  /// Size: 40px, Weight: Regular
  static const TextStyle displayRegular = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.largeDisplay,
    fontWeight: FontWeight.w400,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Heading 1 (28px) =====

  /// Heading 1 - Bold
  /// Size: 28px, Weight: Bold
  /// Used for: Page titles, major sections
  static const TextStyle heading1Bold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading1,
    fontWeight: FontWeight.w700,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 1 - SemiBold
  /// Size: 28px, Weight: SemiBold
  static const TextStyle heading1SemiBold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading1,
    fontWeight: FontWeight.w600,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 1 - Medium
  /// Size: 28px, Weight: Medium
  static const TextStyle heading1Medium = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading1,
    fontWeight: FontWeight.w500,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 1 - Regular
  /// Size: 28px, Weight: Regular
  static const TextStyle heading1Regular = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading1,
    fontWeight: FontWeight.w400,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Heading 2 (24px) =====

  /// Heading 2 - Bold
  /// Size: 24px, Weight: Bold
  /// Used for: Section titles, card titles
  static const TextStyle heading2Bold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading2,
    fontWeight: FontWeight.w700,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 2 - SemiBold
  /// Size: 24px, Weight: SemiBold
  static const TextStyle heading2SemiBold = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading2,
    fontWeight: FontWeight.w600,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 2 - Medium
  /// Size: 24px, Weight: Medium
  static const TextStyle heading2Medium = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading2,
    fontWeight: FontWeight.w500,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Heading 2 - Regular
  /// Size: 24px, Weight: Regular
  static const TextStyle heading2Regular = TextStyle(
    fontFamily: FontFamily.sfProDisplay,
    fontSize: FontSizes.heading2,
    fontWeight: FontWeight.w400,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Large (20px) =====

  /// Large Text - Bold
  /// Size: 20px, Weight: Bold
  /// Used for: Sub-headings, prominent text
  static const TextStyle largeBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraLarge,
    fontWeight: FontWeight.w700,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Large Text - SemiBold
  /// Size: 20px, Weight: SemiBold
  static const TextStyle largeSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraLarge,
    fontWeight: FontWeight.w600,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Large Text - Medium
  /// Size: 20px, Weight: Medium
  static const TextStyle largeMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraLarge,
    fontWeight: FontWeight.w500,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Large Text - Regular
  /// Size: 20px, Weight: Regular
  static const TextStyle largeRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraLarge,
    fontWeight: FontWeight.w400,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Body Large (18px) =====

  /// Body Large - Bold
  /// Size: 18px, Weight: Bold
  static const TextStyle bodyLargeBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.largeExtra,
    fontWeight: FontWeight.w700,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Large - SemiBold
  /// Size: 18px, Weight: SemiBold
  static const TextStyle bodyLargeSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.largeExtra,
    fontWeight: FontWeight.w600,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Large - Medium
  /// Size: 18px, Weight: Medium
  static const TextStyle bodyLargeMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.largeExtra,
    fontWeight: FontWeight.w500,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Large - Regular
  /// Size: 18px, Weight: Regular
  /// Used for: Main body text, descriptions
  static const TextStyle bodyLargeRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.largeExtra,
    fontWeight: FontWeight.w400,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Body (16px) =====

  /// Body - Bold
  /// Size: 16px, Weight: Bold
  static const TextStyle bodyBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.large,
    fontWeight: FontWeight.w700,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body - SemiBold
  /// Size: 16px, Weight: SemiBold
  static const TextStyle bodySemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.large,
    fontWeight: FontWeight.w600,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body - Medium
  /// Size: 16px, Weight: Medium
  static const TextStyle bodyMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.large,
    fontWeight: FontWeight.w500,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body - Regular
  /// Size: 16px, Weight: Regular
  /// Used for: Standard body text
  static const TextStyle bodyRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.large,
    fontWeight: FontWeight.w400,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Body Medium (15px) =====

  /// Body Medium - Bold
  /// Size: 15px, Weight: Bold
  static const TextStyle bodyMediumBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.mediumLarge,
    fontWeight: FontWeight.w700,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Medium - SemiBold
  /// Size: 15px, Weight: SemiBold
  static const TextStyle bodyMediumSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.mediumLarge,
    fontWeight: FontWeight.w600,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Medium - Medium
  /// Size: 15px, Weight: Medium
  static const TextStyle bodyMediumMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.mediumLarge,
    fontWeight: FontWeight.w500,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Medium - Regular
  /// Size: 15px, Weight: Regular
  static const TextStyle bodyMediumRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.mediumLarge,
    fontWeight: FontWeight.w400,
    height: LineHeights.relaxed,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Body Small (14px) =====

  /// Body Small - Bold
  /// Size: 14px, Weight: Bold
  static const TextStyle bodySmallBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.medium,
    fontWeight: FontWeight.w700,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Small - SemiBold
  /// Size: 14px, Weight: SemiBold
  static const TextStyle bodySmallSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.medium,
    fontWeight: FontWeight.w600,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Small - Medium
  /// Size: 14px, Weight: Medium
  static const TextStyle bodySmallMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.medium,
    fontWeight: FontWeight.w500,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  /// Body Small - Regular
  /// Size: 14px, Weight: Regular
  /// Used for: Secondary text, helper text
  static const TextStyle bodySmallRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.medium,
    fontWeight: FontWeight.w400,
    height: LineHeights.normal,
    letterSpacing: LetterSpacings.none,
  );

  // ===== Caption (12px) =====

  /// Caption - Bold
  /// Size: 12px, Weight: Bold
  static const TextStyle captionBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.small,
    fontWeight: FontWeight.w700,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  /// Caption - SemiBold
  /// Size: 12px, Weight: SemiBold
  static const TextStyle captionSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.small,
    fontWeight: FontWeight.w600,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  /// Caption - Medium
  /// Size: 12px, Weight: Medium
  static const TextStyle captionMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.small,
    fontWeight: FontWeight.w500,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  /// Caption - Regular
  /// Size: 12px, Weight: Regular
  /// Used for: Labels, badges, hints
  static const TextStyle captionRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.small,
    fontWeight: FontWeight.w400,
    height: LineHeights.compact,
    letterSpacing: LetterSpacings.tight,
  );

  // ===== Extra Small (10px) =====

  /// Extra Small - Bold
  /// Size: 10px, Weight: Bold
  static const TextStyle extraSmallBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraSmall,
    fontWeight: FontWeight.w700,
    height: LineHeights.tight,
    letterSpacing: LetterSpacings.extraTight,
  );

  /// Extra Small - SemiBold
  /// Size: 10px, Weight: SemiBold
  static const TextStyle extraSmallSemiBold = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraSmall,
    fontWeight: FontWeight.w600,
    height: LineHeights.tight,
    letterSpacing: LetterSpacings.extraTight,
  );

  /// Extra Small - Medium
  /// Size: 10px, Weight: Medium
  static const TextStyle extraSmallMedium = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraSmall,
    fontWeight: FontWeight.w500,
    height: LineHeights.tight,
    letterSpacing: LetterSpacings.extraTight,
  );

  /// Extra Small - Regular
  /// Size: 10px, Weight: Regular
  /// Used for: Tiny labels, timestamps
  static const TextStyle extraSmallRegular = TextStyle(
    fontFamily: FontFamily.sfProText,
    fontSize: FontSizes.extraSmall,
    fontWeight: FontWeight.w400,
    height: LineHeights.tight,
    letterSpacing: LetterSpacings.extraTight,
  );
}

// ============================================================================
// USAGE EXAMPLES
// ============================================================================
//
// Use these text styles in your widgets:
//
// Example 1 - Heading:
//   Text('Title', style: SFProTextStyles.heading1Bold)
//
// Example 2 - Body Text:
//   Text('Body text', style: SFProTextStyles.bodyRegular)
//
// Example 3 - Caption:
//   Text('Small text', style: SFProTextStyles.captionRegular)
//
// Example 4 - Custom style:
//   TextStyle customStyle = SFProTextStyles.bodyRegular.copyWith(
//     color: Colors.blue,
//     letterSpacing: 1.5,
//   )
//
